services:
  voice:
    container_name: voice
    build:
      context: ./voice
      dockerfile: docker/cpu/Dockerfile
    ports:
      - "8880:8880"
    restart: always
    mem_limit: 4G
    cpus: 2
    networks:
      - default
    volumes:
      - voice:/app/backend/data

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - default

  chat:
    container_name: chat
    build:
      context: ./chat
      args:
        OLLAMA_BASE_URL: "/ollama"
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    volumes:
      - chat_data:/app/backend/data
    ports:
      - "${OPEN_WEBUI_PORT-3000}:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
    env_file:
      - ./chat/.env
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - default


  proxy:
    container_name: proxy
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - chat
    networks:
      - default

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./web/.next:/app/.next
    restart: always
    networks:
      - default

volumes:
  chat_data: {}
  voice: {}